<?php

namespace MemberListBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistRepository extends EntityRepository
{
}
